### ISSUE TITLE
Sort the publication list

### ISSUE THREAD

**Issue by mgax** [code4romania/czl-api#3]
I'd like to fetch the publication list, sorted by `_created_at`, so I can see the newest items first, and stop when I reach a publication that I've seen before.

**Comment by xlotlu** [comment]
@mgax: `?ordering=-_created_at` // undocumented_feature
Note that there's no guarantee that you won't get duplicate items between pages, due to the pagination style employed. So you should stop indexing only if you have visited the current item in a previous indexing session.
